project:
  type: book
  output-dir: public

book:
  title: "An introduction to Systematic conservation planning with prioritzr"
  author:
    - "Martin Jung & Louise O'Connor"
  date: today
  margin-header: |
    ![](/resources/IIASA_logo_small)
  favicon: /resources/favicon.ico
  cover-image: /resources/logo.png
  cover-image-alt: |
    An introduction to Systematic conservation planning with prioritzr
  site-url: https://iiasa.github.io/eccb2024/
  search: true
  repo-url: https://github.com/iiasa/eccb2024
  downloads: [pdf]
  page-navigation: true
  sidebar:
    style: docked
    background: light
    border: true
  chapters:
    - index.qmd
    - part: "Introduction to SCP"
      chapters:
        - chapters/intro.qmd
    - part: "Problem creation"
      chapters:
        - chapters/Datapreparation.qmd
        - chapters/Problemcreation.qmd
    - part: "Solving a problem"
      chapters:
        - chapters/SolutionInterpretation.qmd
    - part: "Adding complexity"
      chapters:
        - chapters/ObjectiveFunctions.qmd
        - chapters/ProblemComplexity.qmd
        - chapters/CompareSolutions.qmd
    - part: "Advanced topics"
      chapters:
        - chapters/Connectivity.qmd
        - chapters/Zones.qmd
    - glossary.qmd
    - references.qmd
  appendices:
    - appendices/installation.qmd
    - appendices/FAQ.qmd
  page-footer:
      left: |
        All content licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/) <br> &copy; Martin Jung & Louise O'Connor.
      center: "Supported by the [NaturaConnect](https://naturaconnect.eu) project | ![NaturaConnect](/resources/Natura-Connect-logo.png){width=100, height=20px}"
      right: Built with [Quarto](https://quarto.org/).
      background: "#f8f9fa"

bibliography:
    - references.bib
csl: reference-style.csl

crossrefs-hover: false

format:
  html:
    toc: true
    theme:
      light: flatly
      dark: darkly
    html-math-method: katex
    fontsize: "16px"
    linestretch: 1.6
    mainfont: "Arial"
    monofont: "Fira Mono"
    smooth-scroll: true
    toc-depth: 3
    code-link: false
    code-fold: false
    highlight-style: printing
    code-block-bg: true
    code-overflow: wrap
    reference-location: margin
    mermaid:
      theme: neutral
  pdf:
    documentclass: scrreprt
    margin-left: 30mm
    margin-right: 30mm
