# Glossary {#sec-glossary .unnumbered}

| Term                             | Abbreviation if any | Definition                                                                                                                                                                                                                                                                                                         |
|-----------|-----------|---------------------------------------------------|
| Allocation                       |                     | Synonym use for process taken by the optimization and the decision variable per zone within a PU. Example: Binary decision is to identify expansion or not. The solver allocates PU to a solution based on complementarity.                                                                                        |
| Boundary Length Modifier         | BLM                 | A penalty constant added to a conservation problem that penalizes selecting isolated patches. Results in overall more compact solutions.                                                                                                                                                                           |
| CARE                             | CARE                | A often used abbreviation that stands for ***C**onnectivity*, ***A**dequacy*, ***R**epresentation*, and ***E**ffectiveness* which key principles that should be considered when designing a conservation network. See the [Marxan website](https://marxansolutions.org/the-care-principles/) for more information. |
| Conservation Prioritization      |                     | The computational process of identifying (spatial) priorities for a given conservation objective (such as for identifying protected areas). Usually comes in in the form of a map.                                                                                                                                 |
| Constraint                       |                     | A (often linear) constant or parameter that limits the selection of certain PU as part of the solution.                                                                                                                                                                                                            |
| Cost                             | c                   | A single or multiple constant typically used in SCP to penalize solutions and any allocation of land to PU.                                                                                                                                                                                                        |
| Exact algorithm                  |                     | A method to solve mathematical optimization problems using a solver.                                                                                                                                                                                                                                               |
| Feature                          |                     | Spatial data representing the distribution of an individual biodiversity unit, such as a species, habitat, ecosystem service, etc.                                                                                                                                                                                 |
| Integer                          |                     | In programmatic terms a full number (e.g. -1, 1, 2, 3, ...)                                                                                                                                                                                                                                                        |
| Integer Linear Programming       | ILP                 | Mathematical problem formulation using Linear Programming (ILP) where the variables are integer values and the objective function and equations are linear.                                                                                                                                                        |
| Penalty                          | p                   | In the context of SCP commonly referring to a constant parameter used to penalize solutions. For example a costing or connectivity matrix.                                                                                                                                                                         |
| Planning unit                    | PU                  | The fundamental unit at which decisions in SCP are realized. Can be of multiple formats such as grid cells or farms                                                                                                                                                                                                |
| Solver                           |                     | An algorithm to identify 'solutions' to a mathematical problem. Often available as open- or closed-source software.                                                                                                                                                                                                |
| Systematic Conservation Planning | SCP                 | A framework and step-wise approach towards mapping conservation areas. Usually involves multiple steps such as the identification of a problem and the theory of change, data collection and preparation, conservation prioritization, evaluation and finally implementation. See @margules2000systematic          |
| Zonation                         |                     | A SCP software for creating conservation priority rankings and priority maps and tradeoffs. Uses a meta-heuristic approach and benefit functions for ranking. The latest version is [Zonation 5.](https://zonationteam.github.io/Zonation5/)                                                                       |
| Zone                             | Z                   | Zones are spatial or thematic management units over which decisions are made in a SCP problem. Examples: Core zone, Buffer zone and sustainable management zone in a national park.                                                                                                                                |

: A glossary of key terms used in this Training course
