# Preface {.unnumbered}

Welcome to the training course in systematic conservation planning with the [prioritzr](https://prioritizr.net/ "Website of the prioritzr package"). This training course was originally held at the [2024 European Congress of Conservation biology](https://eccb2024.eu/) in Bologna, although the materials found here will be preserved even after the conference and be openly available to everyone.

## What you will learn

-   The basic concepts of Systematic conservation planning (SCP) and Integer Linear Programming (ILP) in particular
-   How to prepare your input data for a Conservation planning project
-   How to setup and run your first prioritization
-   How outputs can be analysed and interpreted.
-   How to adding complexity factors and changing your conservation planning outcomes
-   Advanced topics such as accounting for connectivity and management zones

Completing all course materials will take you on average 120 minutes, although people who have been exposed to similar methods or introduction before might take less. training materials before might less amount of time.

In this training course a number of different terms will be used. Whenever there are uncertainties with regards to definitions, see the Glossary.

If you have already heard before about the basic concepts of SCP and ILP (For example from the lecture then feel to jump to section 2 and data preparation @sec-dataprep.

::: callout-note
## Before you start...

In order to run the materials on this course website, some preparatory steps need to be taken. Please see the installation instructions in @sec-installation if you have never used **prioritizr** before!
:::
